aimagesite/aimagesite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", views.about, name="about"),
    path("", views.homepage, name="homepage"),
    path("accounts/", include("accounts.urls")),
    path("images/", include("images.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

aimagesite/images/urls.py
from django.urls import path
from .views import (
    ImageUploadView,
    ImageListView,
    ImageDeleteView,
    ImageImproveView,
)
from . import views

app_name = "images"

urlpatterns = [
    path("upload/", ImageUploadView.as_view(), name="upload"),
    path("list/<int:id>/", ImageListView.as_view(), name="image-list"),
    path("delete/<int:pk>/", ImageDeleteView.as_view(), name="image-delete"),
    path("", views.upload_and_improve, name="upload-and-improve"),
    path("<int:image_id>/improve/", views.improve, name="improve"),
    path("improve/<int:pk>/", ImageImproveView.as_view(), name="image-result"),
    path("<int:image_id>/like", views.like, name="like"),
    path("<int:image_id>/dislike", views.dislike, name="dislike"),
]

aimagesite/images/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Image(models.Model):
    name = models.CharField("Name", max_length=20, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    header_image = models.ImageField("Image", null=True, upload_to="ImagesDB/")
    improved_image = models.ImageField(
        "Image", null=True, upload_to="ImagesDB/", blank=True
    )
    feedback = models.BooleanField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("images:image-list", kwargs={"id": self.author_id})

aimagesite/images/forms.py
from django import forms
from .models import Image

VALID_IMAGE_EXTENSIONS = [
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
]


class UploadForm(forms.ModelForm):

    header_image = forms.ImageField(label="Image", required=False)

    url = forms.URLField(
        required=False,
        error_messages={
            "required": "Please enter a valid URL to an image (.jpg .jpeg .png)"
        },
    )

    class Meta:
        model = Image
        fields = ["name", "header_image"]

    def clean_url(self):
        url_text = self.cleaned_data["url"].lower()
        if len(url_text) > 0:
            if not self.valid_url_extension(url_text):
                raise forms.ValidationError(
                    (
                        "Not a valid Image. The URL must have an image extensions (.jpg/.jpeg/.png)"
                    )
                )
        return url_text

    def valid_url_extension(self, url_text, extension_list=VALID_IMAGE_EXTENSIONS):
        return any([url_text.endswith(e) for e in extension_list])

aimagesite/images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import FormView
from django.views.generic import CreateView, ListView, DeleteView, DetailView
from .forms import UploadForm
from .models import Image
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from PIL import Image as PILimage
from urllib.request import urlopen
from io import BytesIO
from django.core.files.base import ContentFile
from django.urls import reverse
from urllib.parse import urlsplit, urlparse
from django.http import HttpResponse, HttpResponseRedirect
import os.path
from django.core.files.images import get_image_dimensions
import http.client
import shutil
import subprocess
import sys


class ImageUploadView(LoginRequiredMixin, FormView):

    form_class = UploadForm
    template_name = "images/upload.html"

    def get_success_url(self):
        return reverse("images:image-list", kwargs={"id": self.request.user.id})

    def form_valid(self, form):
        def _invalidate(msg):
            form.errors["url"] = [
                msg,
            ]
            form.errors["header_image"] = [
                msg,
            ]
            return super(ImageUploadView, self).form_invalid(form)

        form.instance.author = self.request.user

        if "header_image" in form.data and form.data["url"]:
            url = form.data["url"]
            # check if image from url existe
            domain, path = self.split_url(url)
            if not self.image_exists(domain, path):
                return _invalidate(
                    "Couldn't retreive image. (There was an error reaching the server)"
                )

            extension = self.get_file_extension(url)
            fobject = self.retrieve_image(url)
            pil_image = PILimage.open(fobject)
            django_file = self.pil_to_django(pil_image)
            self.imageModel = Image()
            self.imageModel.name = form.instance.name
            self.imageModel.author = form.instance.author
            self.imageModel.header_image.save(
                form.instance.name + extension, django_file
            )
            self.imageModel.save()
            return super().form_valid(form)
        elif not ("header_image" in form.data) and not form.data["url"]:
            self.imageModel = Image()
            self.imageModel.name = form.instance.name
            self.imageModel.author = form.instance.author
            self.imageModel.header_image = form.instance.header_image
            self.imageModel.save()
            return super().form_valid(form)
        elif "header_image" in form.data and not form.data["url"]:
            return _invalidate("Add Image or add Url")
        else:
            return _invalidate("Add either Image or Url not both")

    def retrieve_image(self, url):
        return BytesIO(urlopen(url).read())

    def pil_to_django(self, image, format="PNG"):
        fobject = BytesIO()
        image.save(fobject, format=format)
        return ContentFile(fobject.getvalue())

    def get_file_extension(self, url):
        return os.path.splitext(os.path.basename(urlsplit(url).path))[1]

    def image_exists(self, domain, path):
        try:
            conn = http.client.HTTPConnection(domain)
            conn.request("HEAD", path)
            response = conn.getresponse()
            conn.close()
        except:
            return False
        return response.status == 200

    def split_url(self, url):
        parse_object = urlparse(url)
        return parse_object.netloc, parse_object.path


class ImageListView(LoginRequiredMixin, ListView):

    model = Image
    template_name = "images/user_images_list.html"
    context_object_name = "images"

    def get_queryset(self):

        requested_orderby_column = self.request.GET.get("order_by")
        if requested_orderby_column:
            order_by = requested_orderby_column
        else:
            order_by = "date_posted"

        requested_sort = self.request.GET.get("sort")

        if requested_sort == "asc":
            return Image.objects.filter(author=self.kwargs["id"]).order_by(order_by)
        elif requested_sort == "desc":
            return (
                Image.objects.filter(author=self.kwargs["id"])
                .order_by(order_by)
                .reverse()
            )
        else:
            return (
                Image.objects.filter(author=self.kwargs["id"])
                .order_by(order_by)
                .reverse()
            )


class ImageDeleteView(LoginRequiredMixin, DeleteView):
    model = Image

    def test_func(self):
        image = self.get_object()
        if self.request.user == image.author:
            return True
        return False

    def get_success_url(self):
        image = self.get_object()
        return reverse("images:image-list", kwargs={"id": image.author_id})


class ImageImproveView(DetailView):
    model = Image
    template_name = "images/image_improvement.html"

    def test_func(self):
        image = self.get_object()
        if self.request.user == image.author:
            return True
        return False

    def get_success_url(self):
        image = self.get_object()
        return reverse("images:image-list", kwargs={"id": image.author_id})


def like(request, image_id):

    image = get_object_or_404(Image, pk=image_id)
    image.feedback = 1
    image.save()

    return HttpResponseRedirect(reverse("images:image-list", args=(request.user.id,)))


def dislike(request, image_id):

    image = get_object_or_404(Image, pk=image_id)
    image.feedback = 0
    image.save()

    return HttpResponseRedirect(reverse("images:image-list", args=(request.user.id,)))


def upload_and_improve(request):
    if request.method == "POST":

        if len(request.FILES) == 0:
            return render(
                request,
                "images/homepage.html",
                {"limit_exceeded": False, "no_image": True},
            )

        if request.user.id == None:
            w, h = get_image_dimensions(request.FILES["customFile"])
            if w > 800 or h > 600:
                return render(request, "images/homepage.html", {"limit_exceeded": True})
        else:

            image = Image.objects.create(header_image=request.FILES["customFile"])
            image.save()

            improve_image(image)

            return HttpResponseRedirect(
                reverse("images:image-result", args=(image.id,))
            )
    else:
        return render(request, "images/homepage.html", {"limit_exceeded": False})


def improve(request, image_id):

    image = get_object_or_404(Image, pk=image_id)

    improve_image(image)

    return HttpResponseRedirect(reverse("images:image-result", args=(image.id,)))


def improve_image(image):

    filename = os.path.split(image.header_image.url)[1]
    img_dir_path = os.path.join(
        os.path.split(os.path.abspath(os.path.dirname(__file__)))[0], "media/ImagesDB"
    )
    filepath = os.path.join(img_dir_path, filename)

    if not image.improved_image:
        command = "docker run --rm -v {}:/ne/input alexjc/neural-enhance --zoom=2 input/{}".format(
            img_dir_path, filename
        )
        subprocess.Popen(command, shell=True, stdout=False)

    improved_image_filepath = os.path.join(img_dir_path, filename)

    extension = image.header_image.url.split(".")[1]
    image.improved_image = image.header_image.url.replace(
        "." + extension, "_ne2x.png"
    ).replace("/media/", "")
    image.save()

aimagesite/images/templates/images/home.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

aimagesite/images/templates/images/homepage.html
{% extends 'base_layout.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/compiled/text_animation.css' %}">
<link rel="stylesheet" href="{% static 'css/compiled/home_upload_form.css' %}">
{% endblock %}

{% block content %}

<div class="row">
    <div class="texts">
        <span class="text1">AImage</span>
        <span class="text2">Make your image great again</span>
    </div>
</div>

<div class="upload-wrapper col-sm-12 col-lg-4 mr-auto ml-auto">

    <form action="{% url 'images:upload-and-improve' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="custom-file">
                <input class="custom-file-input" type="file" id="customFile" name="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <input type="submit" value="Submit" class="btn btn-block btn-primary"></input>
    </form>

    {% if no_image %}
        <div style="padding:20px; text-align: center;"><text style="color:red;" class="text-center">Choose the file to improve!</text></div>
    {% endif %}

    {% if limit_exceeded %}
    <div style="padding:20px; text-align: center;"><text style="color:red;" class="text-center">Image dimensions are too
            large!<br> Log in to improve an image of any size.</text></div>
    {% endif %}

</div>

<script src="{% static 'js/set_uploaded_filename.js' %}"></script>
{% endblock %}

aimagesite/images/templates/images/image_confirm_delete.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}Login{% endblock %}
{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/compiled/image_delete_form.css' %}">
{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
    <div class="form-wrapper col-sm-9 col-md-6 col-lg-4">

        <h1 class="text-center">Delete Image</h1>
        <br></br>
        <form class="delete-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h4 align="center"> Are you sure you want to delete image: <i>{{object.name}}</i>?
            </h4>
            <br></br>
            <a class="btn btn-outline-secondary" href="{% url 'images:image-list' object.author_id %}">Cancel</a>
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>

        </form>

    </div>
</div>


{% endblock %}

aimagesite/images/templates/images/image_improvement.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}Login{% endblock %}
{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/compiled/image_results.css' %}">
{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
    <div class="form-wrapper col-sm-9 col-md-6 col-lg-4">

        {% if image.improved_image %}
        <h1 class="text-center">Improvement results</h1>
        {% else %}
        <h1 class="text-center">Improving image...</h1>
        {% endif %}
        <br></br>
        <h2 class="text-center">Original</h2>
        <img src="{{ object.header_image.url }}" width="200" height="200" class="center">
        <br></br>
        <h2 class="text-center">Improved</h2>
        {% if image.improved_image %}
        <a href="{{ object.improved_image.url }}" download="{{ object.improved_image.url }}" class="thumbnail">
            <img src="{{ object.improved_image.url }}" width="200" height="200" class="center"
                onerror="this.onerror=null;this.src='https://media4.giphy.com/media/3oEjI6SIIHBdRxXI40/200.gif'">
        </a>

        {% else %}
        <img src="{% static 'images/spinner.gif' %}" width="200" height="200" class="center">
        {% endif %}

        <br></br>

    </div>
</div>


{% endblock %}

aimagesite/images/templates/images/upload.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}Upload{% endblock %}
{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/compiled/forms.css' %}">
{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
    <div class="form-wrapper col-sm-9 col-md-6 col-lg-4">

        <h1 class="text-center">Upload</h1>

        <form class="site-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Upload">
        </form>

    </div>
</div>


{% endblock %}

aimagesite/images/templates/images/user_images_list.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}Login{% endblock %}
{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/compiled/table.css' %}">

<script src="https://use.fontawesome.com/73387ebe02.js"></script>

{% endblock %}

{% block content %}

{%if images%}
{%if images.first.author.id == user.id%}

<div class="d-flex justify-content-center">
    <a href="{% url 'images:upload' %}" class="btn btn-primary">Upload image</a>
</div>
<div class="d-flex justify-content-center">
    <table class="styled-table">
        <thead>
            <tr>
                <th>
                    <div class="btn-group" role="group">
                        Name
                        <div class="btn-group-vertical">
                            <a href="?order_by=name&sort=asc">
                                <i class="fa fa-sort-up"></i>
                            </a>
                            <a href="?order_by=name&sort=desc">
                                <i class="fa fa-sort-down"></i>
                            </a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="btn-group" role="group">
                        Date
                        <div class="btn-group-vertical">
                            <a href="?order_by=date_posted&sort=asc">
                                <i class="fa fa-sort-up"></i>
                            </a>
                            <a href="?order_by=date_posted&sort=desc">
                                <i class="fa fa-sort-down"></i>
                            </a>
                        </div>
                    </div>
                </th>
                <th>Image</th>
                <th>Improved Image</th>
                <th>Feedback</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            </tr>
            {% for image in images %}
            <tr>
                <td>{{ image.name}}</td>
                <td>{{ image.date_posted | date:"d M Y"}}</td>
                <td>
                    <a href="{{ image.header_image.url }}" download="{{ image.header_image.url }}" class="thumbnail">
                        <img src="{{ image.header_image.url }}" width="100" height="100">
                    </a>
                </td>
                <td>
                    {% if image.improved_image %}
                    <a href="{{ image.improved_image.url }}" download="{{ image.improved_image.url }}"
                        class="thumbnail">
                        <img src="{{ image.improved_image.url }}" width="100" height="100"
                            onerror="this.onerror=null;this.src='https://media4.giphy.com/media/3oEjI6SIIHBdRxXI40/200.gif'">
                    </a>
                    {% else %}
                    Improve to see the results
                    {% endif %}
                </td>
                <td>
                    {% if image.improved_image %}
                    {% if image.feedback != null %}
                    Thank you for the feedback!
                    {% else %}
                    <a class="btn btn-success" href="{% url 'images:like' image.id%}">
                        <span class="button-like">Like</span></a>
                    <a class="btn btn-danger" href="{% url 'images:dislike' image.id %}">
                        <span class="button-dislike">Dislike</span></a>
                    {% endif %}
                    {% else %}
                    Improve to rate
                    {% endif %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'images:improve' image.id%}">
                        <span class="button-improve"></span></a>
                    <a class="btn btn-outline-danger" href="{% url 'images:image-delete' image.id %}">
                        <span class="button-delete"></span></a>
                </td>

            </tr>
        </tbody>

        {% endfor %}
    </table>
</div>
{%else%}
<div class="d-flex justify-content-center">
    <h1> Access denied</h1>
</div>
{%endif%}
{%else%}

<div class="d-flex justify-content-center">
    <a href="{% url 'images:upload' %}" class="btn btn-primary">Upload image</a>
</div>

<div class="d-flex justify-content-center">
    <h1> No images</h1>
</div>
{%endif%}





{% endblock %}