aimagesite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

aimagesite/aimagesite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", views.about, name="about"),
    path("", views.homepage, name="homepage"),
    path("accounts/", include("accounts.urls")),
    path("images/", include("images.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

aimagesite/images/urls.py
from django.urls import path
from .views import (
    ImageUploadView,
    ImageListView,
    ImageDeleteView,
    ImageImproveView,
)
from . import views

app_name = "images"

urlpatterns = [
    path("upload/", ImageUploadView.as_view(), name="upload"),
    path("list/<int:id>/", ImageListView.as_view(), name="image-list"),
    path("delete/<int:pk>/", ImageDeleteView.as_view(), name="image-delete"),
    path("", views.upload_and_improve, name="upload-and-improve"),
    path("<int:image_id>/improve/", views.improve, name="improve"),
    path("improve/<int:pk>/", ImageImproveView.as_view(), name="image-result"),
    path("<int:image_id>/like", views.like, name="like"),
    path("<int:image_id>/dislike", views.dislike, name="dislike"),
]

aimagesite/aimagesite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'images/homepage.html')
    
def about(request):
    return render(request, 'about.html')

aimagesite/aimagesite/templates/about.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/compiled/about.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
{% endblock %}

{% block content %}
    <h1 class="page-title text-center">About Us</h1>

    <div class="row text-center authors">
        <div class="col-md card">
            <img src="{% static 'images/tomasz.jpg' %}" class="image" alt="Author1">
            <div class="hover-content">
                <div class="align-middle hover-inner">
                    <div>
                        <h2 class="name">Tomasz Strzoda</h2>
                        <p class="copy">Full-Stack Developer</p>
                        <a href="https://github.com/DrDEXT3R/" target="_blank">
                            <input type="image" src="{% static 'images/github.png' %}" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md card">
            <img src="{% static 'images/dawid.png' %}" class="image" alt="Author1">
            <div class="hover-content">
                <div class="align-middle hover-inner">
                    <div>
                        <h2 class="name">Dawid Macha</h2>
                        <p class="copy">Back-End Developer</p>
                        <a href="https://github.com/diejdablju" target="_blank">
                            <input type="image" src="{% static 'images/github.png' %}" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md card">
            <img src="{% static 'images/marek.jpg' %}" class="image" alt="Author1">
            <div class="hover-content">
                <div class="align-middle hover-inner">
                    <div>
                        <h2 class="name">Marek Hermansa</h2>
                        <p class="copy">Back-End Developer</p>
                        <a href="https://github.com/marekhermansa" target="_blank">
                            <input type="image" src="{% static 'images/github.png' %}" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content-block">
        <div class="row text-center">
            <div class="about-text card">
                <p><span>AImage</span> is a website created by three colleagues whose friendship began during their studies. Daily meetings and long hours spent together in the <span>Silesian University of Technology</span> classes resulted in the idea of creating something really needed. <span>AImage</span> is an example of this. The use of artificial intelligence allows you to work miracles and <span>your images can be great again!</span></p>
                <p><span>AImage</span> is also an open-source project. Everyone can see the source code and (if having the appropriate knowledge) make a small contribution to the future development of the project.
                We invite everyone interested to our <span>repository</span> (<a href="https://github.com/DrDEXT3R/AImage/" target="_blank">here</a>), read the README file there and contact with the authors.</p>
            </div>
        </div>
        <div class="location">
            <div class="row text-center">
                <div class="col-md-3 card logo">
                    <div class="logo-inner">
                        <img src="{% static 'images/polsl.png' %}" class="image" alt="SUT">
                    </div>
                </div>
                <div class="col-md card map">
                    <div id="mapid"></div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script src="{% static 'js/map.js' %}"></script>
{% endblock %}

aimagesite/aimagesite/templates/base_layout.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} Homepage {% endblock %} | AImage</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" />
    <link rel="stylesheet" href="{% static 'css/compiled/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block head %}
    {% endblock %}

    {% block stylesheet %}
    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar navbar-default navbar-expand-md">
            <a class="navbar-brand" href="{% url 'homepage' %}"><img src="{% static 'images/logo.png' %}"
                    class="d-inline-block mr-1" alt=""> AImage </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu"
                aria-controls="mainmenu" aria-expanded="false" aria-label="nav toggler">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class="navbar-nav ml-auto">

                    {% if user.is_authenticated %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'images:image-list' user.id %}"> My
                            Images </a></li>
                    {% endif %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'about' %}"> About </a></li>
                    {% if user.is_authenticated %}
                            <li>
                                <form id="logout_form" class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                    {% csrf_token %}
                                    <a class="nav-link" href="javascript:{}" onclick="document.getElementById('logout_form').submit();"> Log Out </a></li>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login' %}"> Log In </a></li>
                            <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:signup' %}"> Sign Up </a></li>
                        {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <div id="particles-js"></div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <script src="{% static 'js/particles.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>